### ISSUE TITLE
关于candy集群模式的疑问

### ISSUE THREAD

**Issue by luooo** [dearcode/candy#11]
请问，candy现在是不是不支持集群模式（多个store，多个notifer）
具体一点：gate如何选择的store2，以及store如何根据region信息计算得到用户B通过notifer2推送。
谢谢~

**Comment by c-wind** [comment]
是通过一致性hash算出来的，具体的我也忘记了是不是已经实现了，现在公司事太多，没继续开发了

**Comment by c-wind** [comment]
@luooo

**Comment by luooo** [comment]
看代码是没有完全实现。期待有时间了能够更新 ：）
